name: Go Test

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.22

    - name: Test build
      run: CGO_ENABLED=0 go build -o fmeflow -ldflags="-X \"github.com/safesoftware/fmeflow-cli/cmd.appVersion=$(echo ${GITHUB_REF} | rev | cut -d'/' -f 1 | rev )\""

    - name: Run tests
      run: go test ./...